#!/usr/bin/env python3
"""Retrain the BMW VIN decoder from real FA (Fahrzeugauftrag) backups.

Each FA XML carries ground truth: vinLong, series (chassis), the 4-char typeKey
(== VIN[3:7]), the model name, and the I-Step (shipment) platform. We learn two
tables from this data and regenerate them as Go source for BOTH the in-project
decoder (internal/zgw) and the standalone module (standalone/bmwzgw):

  fa_typekeys.go  — VIN[3:7] -> {chassis, model, xdrive}  (~648 keys, ~98% unique)
  fa_platform.go  — chassis  -> ISTA platform              (from I-Step)

The 4-char type key is ~98% unique per chassis, so the decoder consults these
tables first and only falls back to the single-char VIN[3] heuristic for unknown
keys. Measured accuracy on the training set: chassis ~43% -> ~99%, platform
~63% -> ~99.9%.

Usage:
    python3 tools/vin-retrain/retrain.py PATH         # PATH = dir of FA *.xml or *.zip
    python3 tools/vin-retrain/retrain.py tests_FA_all # zips are auto-extracted

After running, verify:
    go test ./internal/zgw -run FAAccuracy -v   # (needs /tmp/fa_ground.csv, written here)
"""
import sys, os, re, glob, csv, io, zipfile, collections

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TARGETS = [
    (os.path.join(REPO, "internal/zgw"), "zgw"),
    (os.path.join(REPO, "standalone/bmwzgw"), "bmwzgw"),
]
MARKETS = {"ECE","USA","USE","US","LL","KOR","CHN","JPN","AUS","ROW","SAU","IDN","MEX",
           "BRA","RUS","TWN","THA","ZAF","IND","HK","SGP","AUT","DEU","GBR","FRA","ITA",
           "ESP","JAP","CHL","COL","ARE","ISR"}
DTSET = {"RWD","AWD","FWD","xDrive","sDrive"}

def series_to_chassis(s):
    return s[:1] + s[2:] if len(s) == 4 and s[1] == "0" else s

def parse_model(name):
    t = name.split()
    if len(t) < 2:
        return ""
    out = []
    for tok in t[1:]:
        if tok in MARKETS or tok in DTSET:
            break
        out.append(tok)
    return " ".join(out)

def iter_xml(path):
    """Yield XML text from a dir of *.xml and/or *.zip (recursively)."""
    if os.path.isfile(path) and path.endswith(".xml"):
        yield open(path, encoding="utf-8", errors="replace").read(); return
    for zp in glob.glob(os.path.join(path, "**/*.zip"), recursive=True):
        with zipfile.ZipFile(zp) as z:
            for n in z.namelist():
                if n.endswith(".xml"):
                    yield z.read(n).decode("utf-8", "replace")
    for xp in glob.glob(os.path.join(path, "**/*.xml"), recursive=True):
        yield open(xp, encoding="utf-8", errors="replace").read()

def extract(path):
    rows = {}
    for s in iter_xml(path):
        vin = re.search(r'vinLong="([^"]+)"', s)
        ser = re.search(r'series="([^"]+)"', s)
        if not (vin and ser):
            continue
        nm = re.search(r'<id name="([^"]+)"', s)
        istep = re.search(r'I-Step[^:]*:\s*([A-Z0-9]+)-', s)
        rows[vin.group(1).strip()] = dict(
            vin=vin.group(1).strip(), series=ser.group(1).strip(),
            name=nm.group(1).strip() if nm else "",
            platform=istep.group(1).strip() if istep else "")
    return list(rows.values())

def build_tables(rows):
    agg = collections.defaultdict(lambda: collections.defaultdict(collections.Counter))
    chp = collections.defaultdict(collections.Counter)
    for r in rows:
        v = r["vin"]
        if len(v) >= 7:
            tk, ch = v[3:7], series_to_chassis(r["series"])
            agg[tk]["c"][ch] += 1
            md = parse_model(r["name"])
            if md:
                agg[tk]["m"][md] += 1
            dt = next((x for x in r["name"].split() if x in DTSET), "")
            if dt:
                agg[tk]["d"][dt] += 1
        if r["platform"]:
            chp[series_to_chassis(r["series"])][r["platform"]] += 1
    top = lambda c: c.most_common(1)[0][0] if c else ""
    typekeys = {tk: (top(agg[tk]["c"]), top(agg[tk]["m"]),
                     top(agg[tk]["d"]) in ("AWD", "xDrive")) for tk in agg}
    platform = {c: p.most_common(1)[0][0] for c, p in chp.items()}
    return typekeys, platform

def write_go(dirpath, pkg, typekeys, platform, n):
    with open(os.path.join(dirpath, "fa_typekeys.go"), "w") as f:
        f.write(f"package {pkg}\n\n")
        f.write("// faEntry is a VIN type-key (VIN[3:7]) record learned from real BMW FA\n")
        f.write("// (Fahrzeugauftrag) backups. chassis is authoritative; model is the trim\n")
        f.write('// designation (e.g. "330i"); xdrive marks all-wheel drive.\n')
        f.write("type faEntry struct {\n\tchassis string\n\tmodel   string\n\txdrive  bool\n}\n\n")
        f.write(f"// faTypeKeys maps VIN[3:7] -> model, learned from {n} FA backups.\n")
        f.write("// Generated by tools/vin-retrain/retrain.py — do not edit by hand.\n")
        f.write("var faTypeKeys = map[string]faEntry{\n")
        for tk in sorted(typekeys):
            ch, md, xd = typekeys[tk]
            f.write(f'\t"{tk}": {{"{ch}", "{md}", {str(xd).lower()}}},\n')
        f.write("}\n")
    with open(os.path.join(dirpath, "fa_platform.go"), "w") as f:
        f.write(f"package {pkg}\n\n")
        f.write("// faChassisPlatform maps chassis -> ISTA platform, learned from the I-Step\n")
        f.write("// field of real BMW FA backups. Generated by tools/vin-retrain/retrain.py.\n")
        f.write("var faChassisPlatform = map[string]string{\n")
        for c in sorted(platform):
            f.write(f'\t"{c}": "{platform[c]}",\n')
        f.write("}\n")

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    rows = extract(sys.argv[1])
    if not rows:
        print("no FA records found in", sys.argv[1]); sys.exit(1)
    typekeys, platform = build_tables(rows)
    with open("/tmp/fa_ground.csv", "w", newline="") as f:
        w = csv.writer(f); w.writerow(["vin", "series", "typeKey", "platform", "name"])
        for r in rows:
            w.writerow([r["vin"], r["series"], r["vin"][3:7] if len(r["vin"]) >= 7 else "",
                        r["platform"], r["name"]])
    for dirpath, pkg in TARGETS:
        write_go(dirpath, pkg, typekeys, platform, len(rows))
        print(f"wrote {dirpath}/fa_typekeys.go ({len(typekeys)} keys), fa_platform.go ({len(platform)} chassis)")
    print(f"VINs: {len(rows)}  | ground truth: /tmp/fa_ground.csv")
    print("next: gofmt -w internal/zgw/fa_*.go standalone/bmwzgw/fa_*.go && "
          "go test ./internal/zgw -run FAAccuracy -v")

if __name__ == "__main__":
    main()
